// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExportCursor.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ExportCursor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace fnord {
namespace feeds {

namespace {

const ::google::protobuf::Descriptor* ExportCursor_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExportCursor_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ExportCursor_2eproto() {
  protobuf_AddDesc_ExportCursor_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ExportCursor.proto");
  GOOGLE_CHECK(file != NULL);
  ExportCursor_descriptor_ = file->message_type(0);
  static const int ExportCursor_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExportCursor, topic_cursor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExportCursor, head_sequence_),
  };
  ExportCursor_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExportCursor_descriptor_,
      ExportCursor::default_instance_,
      ExportCursor_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExportCursor, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExportCursor, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExportCursor));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ExportCursor_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExportCursor_descriptor_, &ExportCursor::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ExportCursor_2eproto() {
  delete ExportCursor::default_instance_;
  delete ExportCursor_reflection_;
}

void protobuf_AddDesc_ExportCursor_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::fnord::feeds::protobuf_AddDesc_TopicCursor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022ExportCursor.proto\022\013fnord.feeds\032\021Topic"
    "Cursor.proto\"U\n\014ExportCursor\022.\n\014topic_cu"
    "rsor\030\001 \002(\0132\030.fnord.feeds.TopicCursor\022\025\n\r"
    "head_sequence\030\002 \002(\r", 139);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ExportCursor.proto", &protobuf_RegisterTypes);
  ExportCursor::default_instance_ = new ExportCursor();
  ExportCursor::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ExportCursor_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ExportCursor_2eproto {
  StaticDescriptorInitializer_ExportCursor_2eproto() {
    protobuf_AddDesc_ExportCursor_2eproto();
  }
} static_descriptor_initializer_ExportCursor_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ExportCursor::kTopicCursorFieldNumber;
const int ExportCursor::kHeadSequenceFieldNumber;
#endif  // !_MSC_VER

ExportCursor::ExportCursor()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fnord.feeds.ExportCursor)
}

void ExportCursor::InitAsDefaultInstance() {
  topic_cursor_ = const_cast< ::fnord::feeds::TopicCursor*>(&::fnord::feeds::TopicCursor::default_instance());
}

ExportCursor::ExportCursor(const ExportCursor& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fnord.feeds.ExportCursor)
}

void ExportCursor::SharedCtor() {
  _cached_size_ = 0;
  topic_cursor_ = NULL;
  head_sequence_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExportCursor::~ExportCursor() {
  // @@protoc_insertion_point(destructor:fnord.feeds.ExportCursor)
  SharedDtor();
}

void ExportCursor::SharedDtor() {
  if (this != default_instance_) {
    delete topic_cursor_;
  }
}

void ExportCursor::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExportCursor::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExportCursor_descriptor_;
}

const ExportCursor& ExportCursor::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ExportCursor_2eproto();
  return *default_instance_;
}

ExportCursor* ExportCursor::default_instance_ = NULL;

ExportCursor* ExportCursor::New() const {
  return new ExportCursor;
}

void ExportCursor::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_topic_cursor()) {
      if (topic_cursor_ != NULL) topic_cursor_->::fnord::feeds::TopicCursor::Clear();
    }
    head_sequence_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExportCursor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fnord.feeds.ExportCursor)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .fnord.feeds.TopicCursor topic_cursor = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_topic_cursor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_head_sequence;
        break;
      }

      // required uint32 head_sequence = 2;
      case 2: {
        if (tag == 16) {
         parse_head_sequence:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &head_sequence_)));
          set_has_head_sequence();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fnord.feeds.ExportCursor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fnord.feeds.ExportCursor)
  return false;
#undef DO_
}

void ExportCursor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fnord.feeds.ExportCursor)
  // required .fnord.feeds.TopicCursor topic_cursor = 1;
  if (has_topic_cursor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->topic_cursor(), output);
  }

  // required uint32 head_sequence = 2;
  if (has_head_sequence()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->head_sequence(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fnord.feeds.ExportCursor)
}

::google::protobuf::uint8* ExportCursor::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fnord.feeds.ExportCursor)
  // required .fnord.feeds.TopicCursor topic_cursor = 1;
  if (has_topic_cursor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->topic_cursor(), target);
  }

  // required uint32 head_sequence = 2;
  if (has_head_sequence()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->head_sequence(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fnord.feeds.ExportCursor)
  return target;
}

int ExportCursor::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .fnord.feeds.TopicCursor topic_cursor = 1;
    if (has_topic_cursor()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->topic_cursor());
    }

    // required uint32 head_sequence = 2;
    if (has_head_sequence()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->head_sequence());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExportCursor::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExportCursor* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExportCursor*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExportCursor::MergeFrom(const ExportCursor& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_topic_cursor()) {
      mutable_topic_cursor()->::fnord::feeds::TopicCursor::MergeFrom(from.topic_cursor());
    }
    if (from.has_head_sequence()) {
      set_head_sequence(from.head_sequence());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExportCursor::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExportCursor::CopyFrom(const ExportCursor& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExportCursor::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_topic_cursor()) {
    if (!this->topic_cursor().IsInitialized()) return false;
  }
  return true;
}

void ExportCursor::Swap(ExportCursor* other) {
  if (other != this) {
    std::swap(topic_cursor_, other->topic_cursor_);
    std::swap(head_sequence_, other->head_sequence_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExportCursor::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExportCursor_descriptor_;
  metadata.reflection = ExportCursor_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace feeds
}  // namespace fnord

// @@protoc_insertion_point(global_scope)
