// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopicCursor.proto

#ifndef PROTOBUF_TopicCursor_2eproto__INCLUDED
#define PROTOBUF_TopicCursor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace fnord {
namespace feeds {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TopicCursor_2eproto();
void protobuf_AssignDesc_TopicCursor_2eproto();
void protobuf_ShutdownFile_TopicCursor_2eproto();

class TopicCursorOffset;
class TopicCursor;

// ===================================================================

class TopicCursorOffset : public ::google::protobuf::Message {
 public:
  TopicCursorOffset();
  virtual ~TopicCursorOffset();

  TopicCursorOffset(const TopicCursorOffset& from);

  inline TopicCursorOffset& operator=(const TopicCursorOffset& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TopicCursorOffset& default_instance();

  void Swap(TopicCursorOffset* other);

  // implements Message ----------------------------------------------

  TopicCursorOffset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TopicCursorOffset& from);
  void MergeFrom(const TopicCursorOffset& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 next_offset = 5;
  inline bool has_next_offset() const;
  inline void clear_next_offset();
  static const int kNextOffsetFieldNumber = 5;
  inline ::google::protobuf::uint64 next_offset() const;
  inline void set_next_offset(::google::protobuf::uint64 value);

  // required string host_id = 4;
  inline bool has_host_id() const;
  inline void clear_host_id();
  static const int kHostIdFieldNumber = 4;
  inline const ::std::string& host_id() const;
  inline void set_host_id(const ::std::string& value);
  inline void set_host_id(const char* value);
  inline void set_host_id(const char* value, size_t size);
  inline ::std::string* mutable_host_id();
  inline ::std::string* release_host_id();
  inline void set_allocated_host_id(::std::string* host_id);

  // @@protoc_insertion_point(class_scope:fnord.feeds.TopicCursorOffset)
 private:
  inline void set_has_next_offset();
  inline void clear_has_next_offset();
  inline void set_has_host_id();
  inline void clear_has_host_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 next_offset_;
  ::std::string* host_id_;
  friend void  protobuf_AddDesc_TopicCursor_2eproto();
  friend void protobuf_AssignDesc_TopicCursor_2eproto();
  friend void protobuf_ShutdownFile_TopicCursor_2eproto();

  void InitAsDefaultInstance();
  static TopicCursorOffset* default_instance_;
};
// -------------------------------------------------------------------

class TopicCursor : public ::google::protobuf::Message {
 public:
  TopicCursor();
  virtual ~TopicCursor();

  TopicCursor(const TopicCursor& from);

  inline TopicCursor& operator=(const TopicCursor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TopicCursor& default_instance();

  void Swap(TopicCursor* other);

  // implements Message ----------------------------------------------

  TopicCursor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TopicCursor& from);
  void MergeFrom(const TopicCursor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string topic = 1;
  inline bool has_topic() const;
  inline void clear_topic();
  static const int kTopicFieldNumber = 1;
  inline const ::std::string& topic() const;
  inline void set_topic(const ::std::string& value);
  inline void set_topic(const char* value);
  inline void set_topic(const char* value, size_t size);
  inline ::std::string* mutable_topic();
  inline ::std::string* release_topic();
  inline void set_allocated_topic(::std::string* topic);

  // repeated .fnord.feeds.TopicCursorOffset offsets = 2;
  inline int offsets_size() const;
  inline void clear_offsets();
  static const int kOffsetsFieldNumber = 2;
  inline const ::fnord::feeds::TopicCursorOffset& offsets(int index) const;
  inline ::fnord::feeds::TopicCursorOffset* mutable_offsets(int index);
  inline ::fnord::feeds::TopicCursorOffset* add_offsets();
  inline const ::google::protobuf::RepeatedPtrField< ::fnord::feeds::TopicCursorOffset >&
      offsets() const;
  inline ::google::protobuf::RepeatedPtrField< ::fnord::feeds::TopicCursorOffset >*
      mutable_offsets();

  // @@protoc_insertion_point(class_scope:fnord.feeds.TopicCursor)
 private:
  inline void set_has_topic();
  inline void clear_has_topic();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* topic_;
  ::google::protobuf::RepeatedPtrField< ::fnord::feeds::TopicCursorOffset > offsets_;
  friend void  protobuf_AddDesc_TopicCursor_2eproto();
  friend void protobuf_AssignDesc_TopicCursor_2eproto();
  friend void protobuf_ShutdownFile_TopicCursor_2eproto();

  void InitAsDefaultInstance();
  static TopicCursor* default_instance_;
};
// ===================================================================


// ===================================================================

// TopicCursorOffset

// required uint64 next_offset = 5;
inline bool TopicCursorOffset::has_next_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TopicCursorOffset::set_has_next_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TopicCursorOffset::clear_has_next_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TopicCursorOffset::clear_next_offset() {
  next_offset_ = GOOGLE_ULONGLONG(0);
  clear_has_next_offset();
}
inline ::google::protobuf::uint64 TopicCursorOffset::next_offset() const {
  // @@protoc_insertion_point(field_get:fnord.feeds.TopicCursorOffset.next_offset)
  return next_offset_;
}
inline void TopicCursorOffset::set_next_offset(::google::protobuf::uint64 value) {
  set_has_next_offset();
  next_offset_ = value;
  // @@protoc_insertion_point(field_set:fnord.feeds.TopicCursorOffset.next_offset)
}

// required string host_id = 4;
inline bool TopicCursorOffset::has_host_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TopicCursorOffset::set_has_host_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TopicCursorOffset::clear_has_host_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TopicCursorOffset::clear_host_id() {
  if (host_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_id_->clear();
  }
  clear_has_host_id();
}
inline const ::std::string& TopicCursorOffset::host_id() const {
  // @@protoc_insertion_point(field_get:fnord.feeds.TopicCursorOffset.host_id)
  return *host_id_;
}
inline void TopicCursorOffset::set_host_id(const ::std::string& value) {
  set_has_host_id();
  if (host_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_id_ = new ::std::string;
  }
  host_id_->assign(value);
  // @@protoc_insertion_point(field_set:fnord.feeds.TopicCursorOffset.host_id)
}
inline void TopicCursorOffset::set_host_id(const char* value) {
  set_has_host_id();
  if (host_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_id_ = new ::std::string;
  }
  host_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:fnord.feeds.TopicCursorOffset.host_id)
}
inline void TopicCursorOffset::set_host_id(const char* value, size_t size) {
  set_has_host_id();
  if (host_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_id_ = new ::std::string;
  }
  host_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fnord.feeds.TopicCursorOffset.host_id)
}
inline ::std::string* TopicCursorOffset::mutable_host_id() {
  set_has_host_id();
  if (host_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:fnord.feeds.TopicCursorOffset.host_id)
  return host_id_;
}
inline ::std::string* TopicCursorOffset::release_host_id() {
  clear_has_host_id();
  if (host_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = host_id_;
    host_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TopicCursorOffset::set_allocated_host_id(::std::string* host_id) {
  if (host_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete host_id_;
  }
  if (host_id) {
    set_has_host_id();
    host_id_ = host_id;
  } else {
    clear_has_host_id();
    host_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:fnord.feeds.TopicCursorOffset.host_id)
}

// -------------------------------------------------------------------

// TopicCursor

// required string topic = 1;
inline bool TopicCursor::has_topic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TopicCursor::set_has_topic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TopicCursor::clear_has_topic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TopicCursor::clear_topic() {
  if (topic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    topic_->clear();
  }
  clear_has_topic();
}
inline const ::std::string& TopicCursor::topic() const {
  // @@protoc_insertion_point(field_get:fnord.feeds.TopicCursor.topic)
  return *topic_;
}
inline void TopicCursor::set_topic(const ::std::string& value) {
  set_has_topic();
  if (topic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    topic_ = new ::std::string;
  }
  topic_->assign(value);
  // @@protoc_insertion_point(field_set:fnord.feeds.TopicCursor.topic)
}
inline void TopicCursor::set_topic(const char* value) {
  set_has_topic();
  if (topic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    topic_ = new ::std::string;
  }
  topic_->assign(value);
  // @@protoc_insertion_point(field_set_char:fnord.feeds.TopicCursor.topic)
}
inline void TopicCursor::set_topic(const char* value, size_t size) {
  set_has_topic();
  if (topic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    topic_ = new ::std::string;
  }
  topic_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fnord.feeds.TopicCursor.topic)
}
inline ::std::string* TopicCursor::mutable_topic() {
  set_has_topic();
  if (topic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    topic_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:fnord.feeds.TopicCursor.topic)
  return topic_;
}
inline ::std::string* TopicCursor::release_topic() {
  clear_has_topic();
  if (topic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = topic_;
    topic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TopicCursor::set_allocated_topic(::std::string* topic) {
  if (topic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete topic_;
  }
  if (topic) {
    set_has_topic();
    topic_ = topic;
  } else {
    clear_has_topic();
    topic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:fnord.feeds.TopicCursor.topic)
}

// repeated .fnord.feeds.TopicCursorOffset offsets = 2;
inline int TopicCursor::offsets_size() const {
  return offsets_.size();
}
inline void TopicCursor::clear_offsets() {
  offsets_.Clear();
}
inline const ::fnord::feeds::TopicCursorOffset& TopicCursor::offsets(int index) const {
  // @@protoc_insertion_point(field_get:fnord.feeds.TopicCursor.offsets)
  return offsets_.Get(index);
}
inline ::fnord::feeds::TopicCursorOffset* TopicCursor::mutable_offsets(int index) {
  // @@protoc_insertion_point(field_mutable:fnord.feeds.TopicCursor.offsets)
  return offsets_.Mutable(index);
}
inline ::fnord::feeds::TopicCursorOffset* TopicCursor::add_offsets() {
  // @@protoc_insertion_point(field_add:fnord.feeds.TopicCursor.offsets)
  return offsets_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::fnord::feeds::TopicCursorOffset >&
TopicCursor::offsets() const {
  // @@protoc_insertion_point(field_list:fnord.feeds.TopicCursor.offsets)
  return offsets_;
}
inline ::google::protobuf::RepeatedPtrField< ::fnord::feeds::TopicCursorOffset >*
TopicCursor::mutable_offsets() {
  // @@protoc_insertion_point(field_mutable_list:fnord.feeds.TopicCursor.offsets)
  return &offsets_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace feeds
}  // namespace fnord

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TopicCursor_2eproto__INCLUDED
